# Generated by Django 4.2.3 on 2023-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=6, verbose_name='Группа')),
                ('email', models.EmailField(max_length=254, verbose_name='Адресс электронной почты')),
                ('test_level', models.IntegerField(verbose_name='Уровень способностей')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', models.TextField(max_length=250, verbose_name='Описание теста')),
                ('required_level', models.IntegerField(verbose_name='Требуемый уровень')),
                ('resulting_level', models.IntegerField(verbose_name='Получаемый уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(max_length=250, verbose_name='Описание работы')),
                ('required_level', models.IntegerField(verbose_name='Требуемый уровень')),
            ],
        ),
    ]
